# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05823a56f43edfd4e8115fca9316f42e0ac02d91290618b9bbf73e1ec7c6e2e656be731297d8523f16d8a30f289db07a00f79a4ea8c60bb7034899df41209b75

test:
  secret_key_base: f42d88c0a787e3a603db645fc06560298668c1be2232d06fdeb79079fe4ec0eeff995a4378484e1f6596c8e185849bb832280d3a55064f1483042259727c9e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
