Place.create(code: 01, name_kanji: 'Jollibee', name_kana: 'Jollibee', abbreviation: 'abbreviation qwerty', zipcode: '1700', prefecture: 'Akita', city: 'Akita', address: '1234 dollar st. orichimaru village', tel1: '098123', tel2: '547900')
Place.create(code: 02, name_kanji: 'Mcdonald', name_kana: 'Mcdonald', abbreviation: 'abbreviation ytrewq', zipcode: '1000', prefecture: 'Kanagawa', city: 'Yokohama', address: '1234 dollar st. sakura village', tel1: '987345', tel2: '320198')
Place.create(code: 03, name_kanji: 'Burger King', name_kana: 'Burger King', abbreviation: 'abbreviation zxcvb', zipcode: '9000', prefecture: 'Mie', city: 'Tsu', address: '1234 dollar st. sasuke village', tel1: '987234', tel2: '321654')
Place.create(code: 04, name_kanji: 'Asus', name_kana: 'Asus', abbreviation: 'abbreviation bvcxz', zipcode: '3000', prefecture: 'Yamaguchi', city: 'Yamaguchi', address: '1234 dollar st. naruto village', tel1: '764789', tel2: '951357')
Place.create(code: 05, name_kanji: 'Samsung', name_kana: 'Samsung', abbreviation: 'abbreviation coffee', zipcode: '0000', prefecture: 'Miyagi', city: 'Sendai', address: '1234 dollar st. sempai village', tel1: '654951', tel2: '753456')

Trader.create(code: 01, name_kanji: 'Jollibee Foods Corporation', name_kana: 'Jollibee Foods Corporation', tel_name: 'Philip company No.', tel: '098123', fax_name: 'Philip fax No.', fax: '547900', email: 'Philip@gmail.com1', division: 'dibesyon I', memo: 'is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy ', industriaial_waste_excellent_certification_type: 'DOTA',)
Trader.create(code: 02, name_kanji: "McDonald's Corporation", name_kana: "McDonald's Corporation", tel_name: 'Edwards company No.', tel: '987345', fax_name: 'Edwards fax No.', fax: '320198', email: 'Edwards@gmail.com2', division: 'dibesyon II', memo: 'text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', industriaial_waste_excellent_certification_type: 'Starcraft',)
Trader.create(code: 03, name_kanji: 'Burger King Corporation', name_kana: 'Burger King Corporation', tel_name: 'Jay company No.', tel: '987234', fax_name: 'Jay fax No.', fax: '321654', email: 'Jay@gmail.com3', division: 'dibesyon III', memo: 'It has survived not only five centuries, but also the leap into electronic ', industriaial_waste_excellent_certification_type: 'Outlast',)
Trader.create(code: 04, name_kanji: 'AsusTek Computer Inc', name_kana: 'AsusTek Computer Inc', tel_name: 'PhilipPwet company No.', tel: '764789', fax_name: 'PhilipPwet fax No.', fax: '951357', email: 'PhilipPwet@gmail.com4', division: 'dibesyon IV', memo: 'typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem ', industriaial_waste_excellent_certification_type: 'LOL',)
Trader.create(code: 05, name_kanji: 'Samsung Electronics Co., Ltd', name_kana: 'Samsung Electronics Co., Ltd', tel_name: 'Kopiko company No.', tel: '654951', fax_name: 'Kopiko fax No.', fax: '753456', email: 'Kopiko@gmail.com5', division: 'dibesyon V', memo: 'Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum', industriaial_waste_excellent_certification_type: 'Warframe',)

WasteType.create(code: 01, name: 'Industrial')
WasteType.create(code: 02, name: 'General waste')
WasteType.create(code: 03, name: 'Special control industrial waste')
WasteType.create(code: 04, name: 'Business system general waste')
WasteType.create(code: 05, name: 'Household waste')

Unit.create(code: 01, name: 'T')
Unit.create(code: 02, name: 'M3')
Unit.create(code: 03, name: 'Kg')
Unit.create(code: 04, name: 'Liter')
Unit.create(code: 05, name: 'Individuals')

Shape.create(code: 01, name: 'Solid state')
Shape.create(code: 02, name: 'Muddy')
Shape.create(code: 03, name: 'Liquid')
Shape.create(code: 04, name: 'Gas')

Role.create(name: 'Emission company')
Role.create(name: 'Collection and transport company')
Role.create(name: 'Processing company')
Role.create(name: 'Emission operator registration personnel')

Package.create(code: 01, name: 'Rose')
Package.create(code: 02, name: 'Container')
Package.create(code: 03, name: 'Drum')
Package.create(code: 04, name: 'Oil can')
Package.create(code: 05, name: 'Plastic container')

HazardousSubstance.create(code: 01, name: 'Powder or its compound')
HazardousSubstance.create(code: 02, name: 'Cadmium or its compound')
HazardousSubstance.create(code: 03, name: 'Lead or its compound')
HazardousSubstance.create(code: 04, name: 'Organic phosphorus compound')
HazardousSubstance.create(code: 05, name: 'Hexavalent chromium compound')

DisposalMethod.create(code: 01, name: 'Regeneration')
DisposalMethod.create(code: 02, name: 'Reuse (reuse)')
DisposalMethod.create(code: 03, name: 'Material reproduction')
DisposalMethod.create(code: 04, name: 'Other use Raw materialization')
DisposalMethod.create(code: 05, name: 'Fuelization')

EdiUser.create(subscriber_number: 01, connection_registration_number: '000123', published_confirmation_number: '000321', password: 'password', registration_user1_name: 'User I', registration_user1_email: 'UserI@gmail.com', registration_user2_name: 'User jay I', registration_user2_email: 'UserjayI@gmail.com', registration_user3_name: 'User eds I', registration_user3_email: 'UseredsI@gmail.com')
EdiUser.create(subscriber_number: 02, connection_registration_number: '000345', published_confirmation_number: '000957', password: '1234567890', registration_user1_name: 'User II', registration_user1_email: 'UserII@gmail.com', registration_user2_name: 'User jay II', registration_user2_email: 'UserjayII@gmail.com', registration_user3_name: 'User eds II', registration_user3_email: 'UseredsII@gmail.com')
EdiUser.create(subscriber_number: 03, connection_registration_number: '000678', published_confirmation_number: '000318', password: 'qwertyuiop', registration_user1_name: 'User III', registration_user1_email: 'UserIII@gmail.com', registration_user2_name: 'User jay III', registration_user2_email: 'UserjayIII@gmail.com', registration_user3_name: 'User eds III', registration_user3_email: 'UseredsIII@gmail.com')
EdiUser.create(subscriber_number: 04, connection_registration_number: '000890', published_confirmation_number: '000359', password: 'asdfghjkl', registration_user1_name: 'User IV', registration_user1_email: 'UserIV@gmail.com', registration_user2_name: 'User jay IV', registration_user2_email: 'UserjayIV@gmail.com', registration_user3_name: 'User eds IV', registration_user3_email: 'UseredsIV@gmail.com')
EdiUser.create(subscriber_number: 05, connection_registration_number: '000951', published_confirmation_number: '000357', password: 'zxcvbnm', registration_user1_name: 'User V', registration_user1_email: 'UserV@gmail.com', registration_user2_name: 'User jay V', registration_user2_email: 'UserjayV@gmail.com', registration_user3_name: 'User eds V', registration_user3_email: 'UseredsV@gmail.com')

Category.create(code: 01, name: 'Plastic')
Category.create(code: 02, name: 'Metal')
Category.create(code: 03, name: 'Paper')
Category.create(code: 04, name: 'Rubber')
Category.create(code: 05, name: 'Oil')

Car.create(car_type: 'Truck', number: 'AAA 777')
Car.create(car_type: 'Car', number: 'AS 9999')
Car.create(car_type: 'Sedan', number: 'ZCD 456')
Car.create(car_type: 'Pick up', number: 'TYU 321')
Car.create(car_type: 'Wagon', number: 'FGH 312')

Permission.create(trader_id: '1', permit_type: '1', permission_type: '1', permit_number: '000321', permitted_waste_classification: '1', permit_name: 'natural waste collection', allowed_area: '2', permitted_municipality: '2', started_at: '3/2/2017', limited_at: '1/16/2017', industrial_waste_paid_certification_cetegory: 'Classification of Hazardous Wastes', permit_pdf: 'SampleonePdf')
Permission.create(trader_id: '2', permit_type: '2', permission_type: '2', permit_number: '000321', permitted_waste_classification: '2', permit_name: 'natural waste collection', allowed_area: '1', permitted_municipality: '1', started_at: '4/1/2016', limited_at: '1/16/2017', industrial_waste_paid_certification_cetegory: 'Waste Generators', permit_pdf: 'SampletwoPdf')
Permission.create(trader_id: '3', permit_type: '3', permission_type: '5', permit_number: '000987', permitted_waste_classification: '3', permit_name: 'chemical waste collection', allowed_area: '4', permitted_municipality: '4', started_at: '5/10/2015', limited_at: '1/16/2017', industrial_waste_paid_certification_cetegory: 'Waste Transporters', permit_pdf: 'SamplethreePdf')
Permission.create(trader_id: '4', permit_type: '4', permission_type: '4', permit_number: '000345', permitted_waste_classification: '4', permit_name: 'rubber waste collection', allowed_area: '5', permitted_municipality: '5', started_at: '6/11/2014', limited_at: '1/16/2017', industrial_waste_paid_certification_cetegory: 'Waste Transport Record or Manifest System', permit_pdf: 'SamplefourPdf')
Permission.create(trader_id: '5', permit_type: '5', permission_type: '3', permit_number: '000381', permitted_waste_classification: '5', permit_name: 'hazardous waste collection', allowed_area: '3', permitted_municipality: '3', started_at: '7/12/2013', limited_at: '1/16/2017', industrial_waste_paid_certification_cetegory: 'Hazardous Waste Storage and Labeling', permit_pdf: 'SamplefivePdf')