## WASTE COMPANIES
#############################################
Trader.create(code: 1, name_kanji: 'Waste Company A', name_kana: 'Waste Company A', tel_name: 'Waste A company No.', tel: 123, fax_name: 'Waste A fax No.', fax: 123, email: 'waste_company_a@gmail.com1', division: 'storage', memo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', industrial_waste_excellent_certification_type: 'WasteloremA') 
Trader.create(code: 2, name_kanji: 'Waste Company B', name_kana: 'Waste Company B', tel_name: 'Waste B company No.', tel: 123, fax_name: 'Waste B fax No.', fax: 123, email: 'waste_company_b@gmail.com2', division: 'transporter', memo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', industrial_waste_excellent_certification_type: 'WasteloremB')
Trader.create(code: 3, name_kanji: 'Waste Company C', name_kana: 'Waste Company C', tel_name: 'Waste C company No.', tel: 123, fax_name: 'Waste C fax No.', fax: 123, email: 'waste_company_c@gmail.com2', division: 'disposer', memo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', industrial_waste_excellent_certification_type: 'WasteloremC')

Place.create(code: 1, abbreviation: 'WC A', zipcode: '0001', prefecture: 'WC A Prefecture', city: 'WC A City', address: 'WC A Address', tel1: '000009', tel2: '000008')
Place.create(code: 2, abbreviation: 'WC B', zipcode: '0002', prefecture: 'WC B Prefecture', city: 'WC B City', address: 'WC B Address', tel1: '000007', tel2: '000006')
Place.create(code: 3, abbreviation: 'WC C', zipcode: '0003', prefecture: 'WC C Prefecture', city: 'WC C City', address: 'WC C Address', tel1: '000005', tel2: '000004')

TraderPlace.create(trader_id: '1', place_id: '1', place_type: 0)
TraderPlace.create(trader_id: '2', place_id: '2', place_type: 0)
TraderPlace.create(trader_id: '3', place_id: '3', place_type: 0)

# UPDATE users SET trader_id = 1, name_kanji = 'Waste User A', name_kana = 'Waste User A' WHERE id = 1;
# UPDATE users SET trader_id = 2, name_kanji = 'Waste User B', name_kana = 'Waste User B' WHERE id = 2;
# UPDATE users SET trader_id = 3, name_kanji = 'Waste User C', name_kana = 'Waste User C' WHERE id = 3;

Place.create(code: 4, abbreviation: 'WC USER A', zipcode: '0001', prefecture: 'WC USER A Prefecture', city: 'WC USER A City', address: 'WC USER A Address', tel1: '000029', tel2: '000028')
Place.create(code: 5, abbreviation: 'WC USER B', zipcode: '0002', prefecture: 'WC USER B Prefecture', city: 'WC USER B City', address: 'WC USER B Address', tel1: '000027', tel2: '000016')
Place.create(code: 6, abbreviation: 'WC USER C', zipcode: '0003', prefecture: 'WC USER C Prefecture', city: 'WC USER C City', address: 'WC USER C Address', tel1: '000035', tel2: '000044')

PlaceUser.create(place_id: '4', user_id: '1')
PlaceUser.create(place_id: '5', user_id: '2')
PlaceUser.create(place_id: '6', user_id: '3')

TraderEdiUser.create(trader_id: '1', edi_user_id: '1', role_id: '2')
TraderEdiUser.create(trader_id: '2', edi_user_id: '2', role_id: '2')
TraderEdiUser.create(trader_id: '3', edi_user_id: '3', role_id: '3')

EdiUser.create(subscriber_number: 1, connection_registration_number: '101001', published_confirmation_number: '000001', password: 'password', registration_user1_name: 'WC I', registration_user1_email: 'wcI@gmail.com', registration_user2_name: 'WC I', registration_user2_email: 'wcI@gmail.com', registration_user3_name: 'WC I', registration_user3_email: 'wcI@gmail.com')
EdiUser.create(subscriber_number: 2, connection_registration_number: '202002', published_confirmation_number: '000002', password: 'password', registration_user1_name: 'WC II', registration_user1_email: 'wcII@gmail.com', registration_user2_name: 'WC II', registration_user2_email: 'wcII@gmail.com', registration_user3_name: 'WC II', registration_user3_email: 'wcII@gmail.com')
EdiUser.create(subscriber_number: 3, connection_registration_number: '303003', published_confirmation_number: '000003', password: 'password', registration_user1_name: 'WC III', registration_user1_email: 'wcIII@gmail.com', registration_user2_name: 'WC III', registration_user2_email: 'wcIII@gmail.com', registration_user3_name: 'WC III', registration_user3_email: 'wcIII@gmail.com')


## EMISSION COMPANY
#############################################
Trader.create(code: 4, name_kanji: 'Emission Company A', name_kana: 'Emission Company A', tel_name: 'Emission A company No.', tel: 123, fax_name: 'Emission A fax No.', fax: 123, email: 'emission_company_a@gmail.com1', memo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', industrial_waste_excellent_certification_type: 'EmissionloremA') 
Trader.create(code: 5, name_kanji: 'Emission Company B', name_kana: 'Emission Company B', tel_name: 'Emission B company No.', tel: 123, fax_name: 'Emission B fax No.', fax: 123, email: 'emission_company_b@gmail.com2', memo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', industrial_waste_excellent_certification_type: 'EmissionloremB')
Trader.create(code: 6, name_kanji: 'Emission Company C', name_kana: 'Emission Company C', tel_name: 'Emission C company No.', tel: 123, fax_name: 'Emission C fax No.', fax: 123, email: 'emission_company_c@gmail.com2', memo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', industrial_waste_excellent_certification_type: 'EmissionloremC')

Place.create(code: 7, abbreviation: 'EC A', zipcode: '0001', prefecture: 'EC A Prefecture', city: 'EC A City', address: 'EC A Address', tel1: '000529', tel2: '000228')
Place.create(code: 8, abbreviation: 'EC B', zipcode: '0002', prefecture: 'EC B Prefecture', city: 'EC B City', address: 'EC B Address', tel1: '000527', tel2: '000116')
Place.create(code: 9, abbreviation: 'EC C', zipcode: '0003', prefecture: 'EC C Prefecture', city: 'EC C City', address: 'EC C Address', tel1: '000135', tel2: '000244')

TraderPlace.create(trader_id: '4', place_id: '7', place_type: 0)
TraderPlace.create(trader_id: '5', place_id: '8', place_type: 0)
TraderPlace.create(trader_id: '6', place_id: '9', place_type: 0)

# UPDATE users SET trader_id = 4, name_kanji = 'Emission User A', name_kana = 'Emission User A' WHERE id = 4;
# UPDATE users SET trader_id = 5, name_kanji = 'Emission User B', name_kana = 'Emission User B' WHERE id = 5;
# UPDATE users SET trader_id = 6, name_kanji = 'Emission User C', name_kana = 'Emission User C' WHERE id = 6;

Place.create(code: 10, abbreviation: 'EC USER A', zipcode: '0001', prefecture: 'EC USER A Prefecture', city: 'EC USER A City', address: 'EC USER A Address', tel1: '000029', tel2: '000028')
Place.create(code: 11, abbreviation: 'EC USER B', zipcode: '0002', prefecture: 'EC USER B Prefecture', city: 'EC USER B City', address: 'EC USER B Address', tel1: '000027', tel2: '000016')
Place.create(code: 12, abbreviation: 'EC USER C', zipcode: '0003', prefecture: 'EC USER C Prefecture', city: 'EC USER C City', address: 'EC USER C Address', tel1: '000035', tel2: '000044')

PlaceUser.create(place_id: '10', user_id: '4')
PlaceUser.create(place_id: '11', user_id: '5')
PlaceUser.create(place_id: '12', user_id: '6')

TraderEdiUser.create(trader_id: '4', edi_user_id: '4', role_id: '1')
TraderEdiUser.create(trader_id: '5', edi_user_id: '5', role_id: '1')
TraderEdiUser.create(trader_id: '6', edi_user_id: '6', role_id: '1')

EdiUser.create(subscriber_number: 4, connection_registration_number: '101041', published_confirmation_number: '001001', password: 'password', registration_user1_name: 'EC I', registration_user1_email: 'ecI@gmail.com', registration_user2_name: 'EC I', registration_user2_email: 'ecI@gmail.com', registration_user3_name: 'EC I', registration_user3_email: 'ecI@gmail.com')
EdiUser.create(subscriber_number: 5, connection_registration_number: '102502', published_confirmation_number: '502002', password: 'password', registration_user1_name: 'EC II', registration_user1_email: 'ecII@gmail.com', registration_user2_name: 'EC II', registration_user2_email: 'ecII@gmail.com', registration_user3_name: 'EC II', registration_user3_email: 'ecII@gmail.com')
EdiUser.create(subscriber_number: 6, connection_registration_number: '303203', published_confirmation_number: '027403', password: 'password', registration_user1_name: 'EC III', registration_user1_email: 'ecIII@gmail.com', registration_user2_name: 'EC III', registration_user2_email: 'ecIII@gmail.com', registration_user3_name: 'EC III', registration_user3_email: 'ecIII@gmail.com')

TraderPlace.create(trader_id: '4', place_id: '13', place_type: 1)
TraderPlace.create(trader_id: '4', place_id: '14', place_type: 1)
TraderPlace.create(trader_id: '5', place_id: '15', place_type: 1)
TraderPlace.create(trader_id: '5', place_id: '16', place_type: 1)
TraderPlace.create(trader_id: '6', place_id: '17', place_type: 1)
TraderPlace.create(trader_id: '6', place_id: '18', place_type: 1)

# EMISSION COMPANY BRANCHES
Place.create(code: 13, name_kanji: 'Emission Company Branch 1-A', name_kana: 'Emission Company Branch 1-A', abbreviation: 'EC-B USER 1-A', zipcode: '0001', prefecture: 'EC-B USER 1-A Prefecture', city: 'EC-B USER 1-A City', address: 'EC-B USER 1-A Address', tel1: '000029', tel2: '000028')
Place.create(code: 14, name_kanji: 'Emission Company Branch 2-A', name_kana: 'Emission Company Branch 2-A', abbreviation: 'EC-B USER 2-A', zipcode: '0001', prefecture: 'EC-B USER 2-A Prefecture', city: 'EC-B USER 2-A City', address: 'EC-B USER 2-A Address', tel1: '000029', tel2: '000028')

Place.create(code: 15, name_kanji: 'Emission Company Branch 1-B', name_kana: 'Emission Company Branch 1-B', abbreviation: 'EC-B USER 1-B', zipcode: '0002', prefecture: 'EC-B USER 1-B Prefecture', city: 'EC-B USER 1-B City', address: 'EC-B USER 1-B Address', tel1: '000027', tel2: '000016')
Place.create(code: 16, name_kanji: 'Emission Company Branch 2-B', name_kana: 'Emission Company Branch 2-B', abbreviation: 'EC-B USER 2-B', zipcode: '0002', prefecture: 'EC-B USER 2-B Prefecture', city: 'EC-B USER 2-B City', address: 'EC-B USER 2-B Address', tel1: '000027', tel2: '000016')

Place.create(code: 17, name_kanji: 'Emission Company Branch 1-C', name_kana: 'Emission Company Branch 1-C', abbreviation: 'EC-B USER 1-C', zipcode: '0003', prefecture: 'EC-B USER 1-C Prefecture', city: 'EC-B USER 1-C City', address: 'EC-B USER 1-C Address', tel1: '000035', tel2: '000044')
Place.create(code: 18, name_kanji: 'Emission Company Branch 2-C', name_kana: 'Emission Company Branch 2-C', abbreviation: 'EC-B USER 2-C', zipcode: '0003', prefecture: 'EC-B USER 2-C Prefecture', city: 'EC-B USER 2-C City', address: 'EC-B USER 2-C Address', tel1: '000035', tel2: '000044')


## MASTER LIST
#############################################
# Role
Role.create(name: 'Emission operators')
Role.create(name: 'Collection and transport operators')
Role.create(name: 'Processing businesses')

# Category
Category.create(code: '0100000', name: 'Cinders (burning shell)')
Category.create(code: '0110000', name: 'Incinerated ash')
Category.create(code: '0111000', name: 'Coal ash')
Category.create(code: '0112000', name: 'Incineration ash of the waste')
Category.create(code: '0120000', name: 'Waste carbon, active carbon')
Category.create(code: '0200000', name: 'Slurry, mud (mubby substance)')
Category.create(code: '0210000', name: 'Organic sludge')
Category.create(code: '0211000', name: 'Sewage sludge')
Category.create(code: '0220000', name: 'Inorganic sludge')
Category.create(code: '0221000', name: 'Construction sludge (excluding surplus soil)')
Category.create(code: '0222000', name: 'Water supply sludge')
Category.create(code: '0300000', name: 'Waste oil')
Category.create(code: '0310000', name: 'General waste oil')
Category.create(code: '0311000', name: 'Mineral oil')
Category.create(code: '0312000', name: 'Containing animal and vegetable oil')
Category.create(code: '0320000', name: 'Waste solvent')
Category.create(code: '0330000', name: 'Solid oil')
Category.create(code: '0340000', name: 'With oil')
Category.create(code: '0400000', name: 'Waste acid')
Category.create(code: '0401000', name: 'Photographic fixing waste liquid')
Category.create(code: '0500000', name: 'Waste alkali')
Category.create(code: '0501000', name: 'Photographic devlopment waste liquid')
Category.create(code: '0600000', name: 'Waste plastic')
Category.create(code: '0601000', name: 'Waste tire')
Category.create(code: '0602000', name: 'Automotive plastic bumper')
Category.create(code: '0603000', name: 'Agricultural plastic waste')
Category.create(code: '0604000', name: 'Plastic waste containers and packaging')
Category.create(code: '0605000', name: 'Styrene foam; expanded polystyrene')
Category.create(code: '0606000', name: 'Urethne foam')
Category.create(code: '0607000', name: 'Expanded polystyrene')
Category.create(code: '0608000', name: 'Construction materials made of polyvinyl chloride')
Category.create(code: '0700000', name: 'Scraps of paper')
Category.create(code: '0710000', name: 'Construction paper scraps')
Category.create(code: '0711000', name: 'Cardboard')
Category.create(code: '0800000', name: 'Wooden chip')
Category.create(code: '0810000', name: 'Wood waste of construction work')
Category.create(code: '0811000', name: 'Harvested timber/ harvestion material')
Category.create(code: '0900000', name: 'Textile waste (natural fiber scrap)')
Category.create(code: '0910000', name: 'Textilewaste of construction work')
Category.create(code: '1000000', name: 'Animal and vegetable waste')
Category.create(code: '4000000', name: 'Animal solid waste')
Category.create(code: '1100000', name: 'Rubber waste (natural rubber waste)')
Category.create(code: '1200000', name: 'Metal scrap (metal waste)')
Category.create(code: '1210000', name: 'Iron and stell scrap')
Category.create(code: '1220000', name: 'Non-ferrous metal scrap')
Category.create(code: '1221000', name: 'Lead tubes, pipes or plate')
Category.create(code: '1222000', name: 'Electric wire waste')
Category.create(code: '1300000', name: 'Glass scraps, concrete waste and ceramics waste')
Category.create(code: '1310000', name: 'Glass scraps')
Category.create(code: '1311000', name: 'Cullet')
Category.create(code: '1312000', name: 'Waste cathode ray tube (side part)')
Category.create(code: '1313000', name: 'Glass waste container packaging')
Category.create(code: '1314000', name: 'Rock wool')
Category.create(code: '1315000', name: 'Asbestos (non dispersion)')
Category.create(code: '1316000', name: 'Glass wool')
Category.create(code: '1317000', name: 'Rock sound absorbing board')
Category.create(code: '1320000', name: 'Ceramics waste')
Category.create(code: '1321000', name: 'Concrete waste')
Category.create(code: '1322000', name: 'Gypsum board')
Category.create(code: '1323000', name: 'Alc (weight concrete)')
Category.create(code: '1400000', name: 'Mine')
Category.create(code: '1401000', name: 'Slug')
Category.create(code: '1500000', name: 'Rubble class (waste caused by newly-built structures,reconstruction or removal)')
Category.create(code: '1501000', name: 'Concrete pieces')
Category.create(code: '1502000', name: 'Asphalt and concrete debris')
Category.create(code: '1600000', name: 'Animal manure excreted from livestock farming')
Category.create(code: '1700000', name: 'Dead bodies of animals (those discharged from livestock farming)')
Category.create(code: '1800000', name: 'Soot and dust (soot, obtained through factory exhaust)')
Category.create(code: '1900000', name: 'Processed for disposal (no. 13 waste)')
Category.create(code: '2000000', name: 'Construction mixed waste')
Category.create(code: '2010000', name: 'Stable construction mixed waste')
Category.create(code: '2020000', name: 'Managed construction mixed waste')
Category.create(code: '2021000', name: 'New construction mixed waste')
Category.create(code: '2022000', name: 'Mixed demolitaion waste')
Category.create(code: '2100000', name: 'Stable mixed waste')
Category.create(code: '2200000', name: 'Managed mixed waste')
Category.create(code: '2300000', name: 'Schlettar dust')
Category.create(code: '2400000', name: 'Industrial waste containing asbestos')
Category.create(code: '2410000', name: 'Construction mixed waste')
Category.create(code: '2420000', name: 'Glass scraps, concrete waste and ceramics waste')
Category.create(code: '2430000', name: 'Waste plastic')
Category.create(code: '2440000', name: 'Rubble class (waste caused by newly-built structures,reconstruction or removal)')
Category.create(code: '2450000', name: 'Scraps of paper')
Category.create(code: '2460000', name: 'Wooden chip')
Category.create(code: '2470000', name: 'Textile waste (natural fiber scrap)')
Category.create(code: '3000000', name: 'Discarded automobile')
Category.create(code: '3010000', name: 'Used motorcycle')
Category.create(code: '3011000', name: 'Bike')
Category.create(code: '3012000', name: 'Bicycle')
Category.create(code: '3100000', name: 'Waste electrical equipment')
Category.create(code: '3101000', name: 'Pachinko waste machine and waste pachi-slot machine')
Category.create(code: '3102000', name: 'Printed circuit board')
Category.create(code: '3103000', name: 'Television receivers')
Category.create(code: '3104000', name: 'Air conditioning')
Category.create(code: '3105000', name: 'Refrigerator')
Category.create(code: '3106000', name: 'Washing machine')
Category.create(code: '3107000', name: 'Micro wave')
Category.create(code: '3108000', name: 'Personal computer')
Category.create(code: '3109000', name: 'Phone')
Category.create(code: '3110000', name: 'Vanding machine')
Category.create(code: '3111000', name: 'Fluorescent lamp')
Category.create(code: '3112000', name: 'Freezer')
Category.create(code: '3200000', name: 'Medical measuring instrument')
Category.create(code: '3211000', name: 'Mercury thermometers')
Category.create(code: '3212000', name: 'Mercury sphygmomameter')
Category.create(code: '3500000', name: 'Waste batteries and accumulators')
Category.create(code: '3510000', name: 'Lead-acid batteries')
Category.create(code: '3520000', name: 'Dry battery')
Category.create(code: '3600000', name: 'Composite material')
Category.create(code: '7000000', name: 'Flammable waste oil (combustable waste oil)')
Category.create(code: '7010000', name: 'Combustible waste (such as those containing hazardous substances exceeding the reference value)')
Category.create(code: '7100000', name: 'Waste acid of ph 2.0 or less')
Category.create(code: '7110000', name: 'Waste acid of ph 2.0 or less (such as those containing hazardous substances exceeding the reference value)')
Category.create(code: '7200000', name: 'Waste alkali of ph 12.5 or more')
Category.create(code: '7210000', name: 'Waste alkali of ph 12.5 or more (such as those containing hazardous substances exceeding the reference value)')
Category.create(code: '7300000', name: 'Infectious waste')
Category.create(code: '7400000', name: 'Specific hazardous industrial waste')
Category.create(code: '7410000', name: 'Pcb waste and pcb contamination, pcb processing')
Category.create(code: '7411000', name: 'Pcb waste')
Category.create(code: '7412000', name: 'Pcb contamination')
Category.create(code: '7413000', name: 'Pcb processing')
Category.create(code: '7440000', name: 'Waste mercury etc.( including those processed for disposal)')
Category.create(code: '7421000', name: 'Waste asbestos etc.(dispersion)')
Category.create(code: '7422000', name: 'Designated sewage sludge')
Category.create(code: '7423000', name: 'Slag (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '7424000', name: 'Burning shell (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '7425000', name: 'Waste oil (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '7426000', name: 'Sludge (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '7427000', name: 'Waste acid (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '7428000', name: 'Waste alkali (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '7429000', name: 'Soot and dust (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '7430000', name: 'Material processed for disposal (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '5010000', name: 'Burning shell')
Category.create(code: '5011000', name: 'Incinerated ash (classification code upper 4digits 5012 to 5014 can not be classified)')
Category.create(code: '5012000', name: 'Incinerated ash (coal ash)')
Category.create(code: '5013000', name: 'Incinerated ash (incineration ash of waste)')
Category.create(code: '5014000', name: 'Incinerated ash (sewage sludge)')
Category.create(code: '5020000', name: 'Sludge')
Category.create(code: '5021000', name: 'Organic sludge (classification code upper4 digits 5022 to 5024 can not be classified)')
Category.create(code: '5022000', name: 'Organic sludge (sewage sludge)')
Category.create(code: '5023000', name: 'Organic sludge (industrial water sludge)')
Category.create(code: '5024000', name: 'Organic sludge (waste compost)')
Category.create(code: '5025000', name: 'Inorganic sludge (classification code can not be classified into 4 digits 5026 to 5027)')
Category.create(code: '5026000', name: 'Inorganic sludge (construction sludge (excluding surplus soil))')
Category.create(code: '5027000', name: 'Inorganic sludge (sewage sludge)')
Category.create(code: '5030000', name: 'Waste oil')
Category.create(code: '5031000', name: 'General waste oil (classification code upper 4 digit 5032 to 5033 can not be classified)')
Category.create(code: '5032000', name: 'General waste oil (mineral oil)')
Category.create(code: '5033000', name: 'General waste oil (animal and vegetable oil)')
Category.create(code: '5034000', name: 'Waste solvents')
Category.create(code: '5035000', name: 'Solid oil')
Category.create(code: '5036000', name: 'With oil')
Category.create(code: '5040000', name: 'Waste acid')
Category.create(code: '5041000', name: 'Photographic fixing waste liquid')
Category.create(code: '5050000', name: 'Waste alkali')
Category.create(code: '5051000', name: 'Photographic devlopment waste liquid')
Category.create(code: '5060000', name: 'Waste plastic')
Category.create(code: '5061000', name: 'Waste tire')
Category.create(code: '5062000', name: 'Automotive plastic bumper')
Category.create(code: '5063000', name: 'Agricultural plastic waste')
Category.create(code: '5064000', name: 'Plastic waste containers and packaging')
Category.create(code: '5065000', name: 'Styrene foam; expanded polystyrene')
Category.create(code: '5066000', name: 'Urethne foam')
Category.create(code: '5067000', name: 'Expanded polystyrene')
Category.create(code: '5068000', name: 'Construction materials made of polyvinyl chloride')
Category.create(code: '5070000', name: 'Scraps of paper')
Category.create(code: '5071000', name: 'Construction paper scraps (other than cardboard)')
Category.create(code: '5072000', name: 'Construction paper scraps (cardboard)')
Category.create(code: '5080000', name: 'Wooden chip')
Category.create(code: '5081000', name: 'Construction wooden chips (other than harvested timber / harvestion material)')
Category.create(code: '5082000', name: 'Construction wooden chips (harvested timber/ harvistion material)')
Category.create(code: '5090000', name: 'Textile waste (natural fiber scrap)')
Category.create(code: '5091000', name: 'Textilewaste of construction work')
Category.create(code: '5110000', name: 'Animal and vegetable waste')
Category.create(code: '5120000', name: 'Animal solid waste')
Category.create(code: '5130000', name: 'Rubber waste (natural rubber waste)')
Category.create(code: '5140000', name: 'Metal scrap (metal waste)')
Category.create(code: '5141000', name: 'Iron and stell scrap')
Category.create(code: '5142000', name: 'Non-ferrous metal scrap (classification code upper 4 digits 5143,5144 can not be classified)')
Category.create(code: '5143000', name: 'Non-ferrous metal scrap (leadpipe or plate)')
Category.create(code: '5144000', name: 'Non-ferrous metal scrap (wire scrap)')
Category.create(code: '5150000', name: 'Glass scraps, concrete waste and ceramics waste')
Category.create(code: '5151000', name: 'Glass scraps (classification code can not be classified into 4 digits 5152 and 5158)')
Category.create(code: '5152000', name: 'Glass scraps (cullet)')
Category.create(code: '5153000', name: 'Glass scraps (waste cathode ray tube ( lateral))')
Category.create(code: '5154000', name: 'Glass scraps (waste containers made of glass)')
Category.create(code: '5155000', name: 'Glass scraps (rock wool)')
Category.create(code: '5156000', name: 'Glass scraps (asbestos (non--dispersible))')
Category.create(code: '5157000', name: 'Glass scraps (glass wool)')
Category.create(code: '5158000', name: 'Glass scraps (rock sound absorbing board)')
Category.create(code: '5161000', name: 'Ceramic waste (classification code upper 4digit 5162,5164 can not be classified)')
Category.create(code: '5162000', name: 'Ceramic waste (concrete waste)')
Category.create(code: '5163000', name: 'Ceramic waste (gypsum board)')
Category.create(code: '5164000', name: 'Ceramic waste ( alc (light weight cellular concrete))')
Category.create(code: '5170000', name: 'Mine')
Category.create(code: '5171000', name: 'Slug')
Category.create(code: '5180000', name: 'Rubble class (waste caused by newly-built structures,reconstruction or removal)')
Category.create(code: '5181000', name: 'Concrete pieces')
Category.create(code: '5182000', name: 'Asphalt and concrete debris')
Category.create(code: '5190000', name: 'Animal manure excreted from livestock farming')
Category.create(code: '5210000', name: 'Dead bodies of animals (those discharged from livestock farming)')
Category.create(code: '5220000', name: 'Soot and dust (soot and dust obtained by treating factory exhaust gas)')
Category.create(code: '5221000', name: 'Soot and dust (soot and dust in waste incinerators)')
Category.create(code: '5222000', name: 'Soot andsust (sewage sludge )')
Category.create(code: '5230000', name: 'Processed for disposal  (no. 13 waste)')
Category.create(code: '5240000', name: 'Construction mixed waste')
Category.create(code: '5241000', name: 'Stable construction mixed waste')
Category.create(code: '5242000', name: 'Managed construction mixed waste (classification code upper 4 digits other than 5243, 5244)')
Category.create(code: '5243000', name: 'Managed construction mixed waste (new construction)')
Category.create(code: '5244000', name: 'Managed construction mixed waste (dismantling system)')
Category.create(code: '5250000', name: 'Stable mixed waste')
Category.create(code: '5260000', name: 'Managed mixed waste')
Category.create(code: '5270000', name: 'Schlettar dust')
Category.create(code: '5281000', name: 'Construction mixed waste')
Category.create(code: '5282000', name: 'Glass scraps, concrete waste and ceramics waste')
Category.create(code: '5283000', name: 'Waste plastic')
Category.create(code: '5284000', name: 'Rubble class ( waste caused by newly-built structures,reconstruction or removal)')
Category.create(code: '5285000', name: 'Scraps of paper')
Category.create(code: '5286000', name: 'Wooden chip')
Category.create(code: '5287000', name: 'Textile waste (natural fiber scrap)')
Category.create(code: '5290000', name: 'Discarded automobile')
Category.create(code: '5291000', name: 'Used motorcycle (things that can not be classified as 4 digits5292 and 5293 on classification code)')
Category.create(code: '5292000', name: 'Used motorcycle (bike)')
Category.create(code: '5293000', name: 'Used motorcycle (bicycle)')
Category.create(code: '5310000', name: 'Waste electrical equipment')
Category.create(code: '5311000', name: 'Pachinko waste machine and waste pachi-slot machine')
Category.create(code: '5312000', name: 'Printed circuit board')
Category.create(code: '5313000', name: 'Television teceivers')
Category.create(code: '5314000', name: 'Air conditioning')
Category.create(code: '5315000', name: 'Refrigerator')
Category.create(code: '5316000', name: 'Washing machine')
Category.create(code: '5317000', name: 'Micro wave')
Category.create(code: '5318000', name: 'Personal computer')
Category.create(code: '5319000', name: 'Phone')
Category.create(code: '5321000', name: 'Vanding machine')
Category.create(code: '5322000', name: 'Fluorescent lamp')
Category.create(code: '5323000', name: 'Freezer')
Category.create(code: '5330000', name: 'Waste batteries')
Category.create(code: '5331000', name: 'Lead storage battery')
Category.create(code: '5332000', name: 'Dry battery')
Category.create(code: '5340000', name: 'Composite material')
Category.create(code: '7510000', name: 'Flammable waste oil (combustable waste oil)')
Category.create(code: '7511000', name: 'Combustible waste (such as those containing hazardous substances exceeding the reference value)')
Category.create(code: '7520000', name: 'Waste acid of ph 2.0 or less')
Category.create(code: '7521000', name: 'Waste acid of ph 2.0 or less (such as those containing hazardous substances exceeding the reference value)')
Category.create(code: '7530000', name: 'Waste alkali of ph 12.5 or more')
Category.create(code: '7531000', name: 'Waste alkali of ph 12.5 or more (such as those containing hazardous substances exceeding the reference value)')
Category.create(code: '7540000', name: 'Infectious waste')
Category.create(code: '7550000', name: 'Specific hazardous industrial waste')
Category.create(code: '7551000', name: 'Waste pcbs (classification code upper 4 digits 7552 to 7554 can not be clasified)')
Category.create(code: '7552000', name: 'Waste pcbs (waste pcb)')
Category.create(code: '7553000', name: 'Waste pcbs (pcb contaminants)')
Category.create(code: '7554000', name: 'Waste pcbs (pcb treated material)')
Category.create(code: '7555000', name: 'Waste asbestos etc.(dispersion)')
Category.create(code: '7556000', name: 'Designated sewage sludge')
Category.create(code: '7557000', name: 'Slag (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '7558000', name: 'Burning shell (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '7559000', name: 'Waste oil (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '7561000', name: 'Sludge (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '7562000', name: 'Waste acid (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '7563000', name: 'Waste alkali (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '7564000', name: 'Soot and dust (one containing a hazardous substance exceeds the standard value)')
Category.create(code: '7565000', name: 'Material processed for disposal (one containing a hazardous substance exceeds the standard value)')

# Unit
Unit.create(code: '1', name: 't')
Unit.create(code: '2', name: 'm3')
Unit.create(code: '3', name: 'kg')
Unit.create(code: '4', name: 'Liter')
Unit.create(code: '5', name: 'Pieces/Unit')

# Package
Package.create(code: '01', name: 'Aparted/Scrap')
Package.create(code: '02', name: 'Container')
Package.create(code: '03', name: 'Drum/Can')
Package.create(code: '04', name: 'Oil tin')
Package.create(code: '05', name: 'Plastic container')
Package.create(code: '06', name: 'Bag')
Package.create(code: '07', name: 'Flexible container bag')
Package.create(code: '08', name: 'Carboard box')
Package.create(code: '09', name: 'Other')

# HazardousSubstance
HazardousSubstance.create(code: '01', name: 'Mercury or its compounds')
HazardousSubstance.create(code: '02', name: 'Cadmium or its compounds')
HazardousSubstance.create(code: '03', name: 'Lead or its compounds')
HazardousSubstance.create(code: '04', name: 'Organic phosphorus compounds')
HazardousSubstance.create(code: '05', name: 'Six valence chrome compounds')
HazardousSubstance.create(code: '06', name: 'Arsenic or its compounds')
HazardousSubstance.create(code: '07', name: 'Cyanogen compounds')
HazardousSubstance.create(code: '08', name: 'Printed cercuit board')
HazardousSubstance.create(code: '09', name: 'Trichloroethylene')
HazardousSubstance.create(code: '10', name: 'Tetrachloroethylene')
HazardousSubstance.create(code: '11', name: 'Dichloro methane')
HazardousSubstance.create(code: '12', name: 'Carbon tetrachloride')
HazardousSubstance.create(code: '13', name: '1,2-Dichloroethane')
HazardousSubstance.create(code: '14', name: '1,1-Dichloroethylene')
HazardousSubstance.create(code: '15', name: 'Cis-1,2-Dichloroethylene')
HazardousSubstance.create(code: '16', name: '1,1,1-Trichloroethane')
HazardousSubstance.create(code: '17', name: '1,1,2-Trichloroethane')
HazardousSubstance.create(code: '18', name: '1,3-Dichloropropene (D-D)')
HazardousSubstance.create(code: '19', name: 'Thiuram')
HazardousSubstance.create(code: '20', name: 'Simazine (CAT)')
HazardousSubstance.create(code: '21', name: 'Thiobencarb (Benthiocarb)')
HazardousSubstance.create(code: '22', name: 'Benzene')
HazardousSubstance.create(code: '23', name: 'Selenium or its compounds')
HazardousSubstance.create(code: '24', name: 'Dioxins (organic chlorine compounds)')
HazardousSubstance.create(code: '25', name: 'Copper or its compound')
HazardousSubstance.create(code: '26', name: 'Zinc or its compounds')
HazardousSubstance.create(code: '27', name: 'Fluoride')
HazardousSubstance.create(code: '28', name: 'Beryllium or its compounds')
HazardousSubstance.create(code: '29', name: 'Chromium or its compounds')
HazardousSubstance.create(code: '30', name: 'Nickel or its compounds')
HazardousSubstance.create(code: '31', name: 'Vanadium or its compound')
HazardousSubstance.create(code: '32', name: 'Phenols')
HazardousSubstance.create(code: '33', name: '1,4-Dioxane')

# DisposalMethod
DisposalMethod.create(code: '100', name: 'Recycle')
DisposalMethod.create(code: '101', name: 'Reuse')
DisposalMethod.create(code: '102', name: 'Reproduction as material')
DisposalMethod.create(code: '103', name: 'Materiarization for other use(Raw material for other use)')
DisposalMethod.create(code: '104', name: 'Fuelization')
DisposalMethod.create(code: '105', name: 'Composting')
DisposalMethod.create(code: '106', name: 'Other recycle')
DisposalMethod.create(code: '200', name: 'Intermediate processing')
DisposalMethod.create(code: '201', name: 'Dehydration')
DisposalMethod.create(code: '202', name: 'Mechanical drying')
DisposalMethod.create(code: '203', name: 'Sun drying')
DisposalMethod.create(code: '204', name: 'Refuse incineration')
DisposalMethod.create(code: '205', name: 'Separating into oil and water')
DisposalMethod.create(code: '206', name: 'Neutralization')
DisposalMethod.create(code: '207', name: 'Crush')
DisposalMethod.create(code: '208', name: 'Compression')
DisposalMethod.create(code: '209', name: 'Melting')
DisposalMethod.create(code: '210', name: 'Sorting')
DisposalMethod.create(code: '211', name: 'Solidification')
DisposalMethod.create(code: '212', name: 'Torrefaction')
DisposalMethod.create(code: '213', name: 'Decomposition')
DisposalMethod.create(code: '214', name: 'Washing')
DisposalMethod.create(code: '215', name: 'Sterilization')
DisposalMethod.create(code: '216', name: 'Disinfaction')
DisposalMethod.create(code: '217', name: 'Boiling')
DisposalMethod.create(code: '299', name: 'Other intermediate processing')
DisposalMethod.create(code: '300', name: 'Final disposal')
DisposalMethod.create(code: '301', name: 'Landfill disposal')
DisposalMethod.create(code: '302', name: 'Stable landfill disposal')
DisposalMethod.create(code: '303', name: 'Managed landfill disposal')
DisposalMethod.create(code: '304', name: 'Blocked landfill disposal')
DisposalMethod.create(code: '310', name: 'Ocean disposal of radioactive waste')

WasteType.create(code: 01, name: 'Industrial')
WasteType.create(code: 02, name: 'General waste')
WasteType.create(code: 03, name: 'Special control industrial waste')
WasteType.create(code: 04, name: 'Business system general waste')
WasteType.create(code: 05, name: 'Household waste')

Shape.create(code: 01, name: 'Solid state')
Shape.create(code: 02, name: 'Muddy')
Shape.create(code: 03, name: 'Liquid')
Shape.create(code: 04, name: 'Gas')